url: https://www.tombarbarbag.com

title: TOMBARBAR

keywords: 

description: 

company: Guangzhou Bloom-Win Fashion Co,. Ltd

address: Room 1108-1109,11/F Caizhi Building,NO.448 Guangzhou Street South,Guangzhou,China

tel: +86-020-89233420

fax: +86-020-89104995

email: jennyl@tombarbarbag.com

facebook: https://www.facebook.com/TombarbarBag/

twitter: https://twitter.com/tombarbarbag

linkedin: https://www.linkedin.com/

youtube: https://www.youtube.com/

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  compress:
    css: true
    js: true
  gzip: []
