url: https://www.tombarbarbag.com

title: TOMBARBAR

keywords: woman fashion bag,woman backpack,woman tote bag,woman messenger bag,woman handbag

description: TOMBARBAR

company: Guangzhou Bloom-Win Fashion Co,. Ltd

address: Room 1108-1109,11/F Caizhi Building,NO.448 Guangzhou Street South,Guangzhou,China

tel: +86-020-89233420

fax: +86-020-89104995

email: jennyl@tombarbarbag.com

facebook: https://www.facebook.com/TombarbarBag/

twitter: https://twitter.com/tombarbarbag

linkedin: https://www.linkedin.com/company/tombarbar/

youtube: https://www.youtube.com/channel/UCg8cnluH3vUBFmhzl0AAezg?view_as=subscriber

vk: https://vk.com/tombarbar

instagram: https://www.instagram.com/tombarbarbag/


exclude:
  - README.md
  - style.css
